package wechatEnum

// MsgTypeEvent ...
var MsgTypeEvent = "event"

// MsgTypeText ...
var MsgTypeText = "text"

// MsgTypeImage ...
var MsgTypeImage = "image"

// MsgTypeVoice ...
var MsgTypeVoice = "voice"

// MsgTypeVideo ...
var MsgTypeVideo = "video"

// MsgTypeShortVideo ...
var MsgTypeShortVideo = "shortvideo"

// MsgTypeLink ...
var MsgTypeLink = "link"

//EventClick ...
var EventClick = "CLICK"

//EventView ...
var EventView = "VIEW"

//EventScanCodePush ...
var EventScanCodePush = "scancode_push"

//EventScanCodeWaitMsg ...
var EventScanCodeWaitMsg = "scancode_waitmsg"

//EventPicSysPhoto ...
var EventPicSysPhoto = "pic_sysphoto"

//EventPicPhotoOrAlbum ...
var EventPicPhotoOrAlbum = "pic_photo_or_album"

//EventPicWeixin ...
var EventPicWeixin = "pic_weixin"

//EventLocationSelect ...
var EventLocationSelect = "location_select"

//EventSubscribe ...
var EventSubscribe = "subscribe"

//EventUnsubscribe ...
var EventUnsubscribe = "unsubscribe"

//EventScan ...
var EventScan = "SCAN"

//EventLocation ..
var EventLocation = "LOCATION"
